import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import { FaStar, FaStarHalfAlt, FaStarHalf, FaRegStar } from 'react-icons/fa'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export default function GuruPage({ id = '' }) {
  return (<>
    <Head>
      <title>{id} Page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="w-full h-screen bg-slate-50">
      <Header />
      <section className="py-10 bg-gray-50 sm:py-16 lg:py-24">
        <div className="px-4 mx-auto sm:px-6 lg:px-8 max-w-7xl">
          <div className="max-w-2xl mx-auto text-center">
            <h2 className="text-3xl font-bold leading-tight text-black sm:text-4xl lg:text-5xl capitalize">{id.split('-').join(' ')}</h2>
            <p className="max-w-xl mx-auto mt-4 text-base leading-relaxed text-gray-600">Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis.</p>
          </div>
        </div>
      </section>
    </main>
  </>)

}

export async function getServerSideProps(context) {
  const id = context.params?.guruId || null
  return {
    props: { id }
  }
}